# DOCKER_BUILDKIT=1 docker image build -f ./Dockerfile.production -t maxmls/events-server:latest .
# docker push maxmls/events-server:latest

FROM node:16-alpine

WORKDIR /app

COPY . .

RUN npm i && npm run build

FROM node:16-alpine
RUN apk add --no-cache bash

COPY --from=0 /app/dist /app

EXPOSE 80

CMD [ "bash", "-c", "node ./app/main.js" ]
